# Generated by Django 6.0.4 on 2026-05-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CivicIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('origin_location', models.CharField(max_length=255)),
                ('issue_details', models.TextField()),
                ('uploaded_image', models.ImageField(upload_to='civic_issues_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Open', max_length=20)),
            ],
        ),
    ]
