# Generated by Django 6.0.4 on 2026-05-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_civicissue_votes_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='civicissue',
            name='assigned_department',
            field=models.CharField(blank=True, choices=[('Water', 'Water Supply & Sewage'), ('Roads', 'Roads & Traffic'), ('Sanitation', 'Sanitation & Waste'), ('Electricity', 'Electricity & Lighting'), ('Health', 'Public Health & Safety'), ('Other', 'Other/General')], default='Other', max_length=50, null=True),
        ),
    ]
